# ENV['HTTP_USER'] = 'devuser'
# ENV['HTTP_PASS'] = 'devpass'

# ENV['ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY'] = 'U29YSJ4FDh0Kpf4utHlusnfVeavDROi9' 
# ENV['ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY'] = 'B4sGBFy67Q2BktMbz5zSmecLsWH9JqDP'
# ENV['ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT'] = 'NzBKK3CpqH4IQSKUxPb12k8wFzEoulnX'